services:
  postgres:
    image: postgres:15
    container_name: pg
    restart: always
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      DB_USERNAME: user
      DB_PASSWORD: pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  pgdata:
